-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:903f47a83952dd426d986f9c9fd43d11$
-- 

return {
	texture = 'battler3.png',
	frames = {
			{
				name = "battler3_1.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 128 },
				uvRect = { u0 = 0, v0 = 0, u1 = 1, v1 = 0.333333 },
				spriteSourceSize = { width = 96, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "battler3_2.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 128 },
				uvRect = { u0 = 0, v0 = 0.333333, u1 = 1, v1 = 0.666667 },
				spriteSourceSize = { width = 96, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "battler3_3.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 128 },
				uvRect = { u0 = 0, v0 = 0.666667, u1 = 1, v1 = 1 },
				spriteSourceSize = { width = 96, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

